### ISSUE TITLE
Solve dispacher's pool updating process

### ISSUE THREAD

**Issue by AntiD2ta** [2kodevs/Distributed-Scrapper#19]
**Is your feature request related to a problem? Please describe.**
Actually we're updating the pool of task to push when we get a result from a scrapper:

```
if len(self.pool) == 0:
                with lockResults:
                    if change:
                        responsedURLs = {html for url, html in self.htmls}
                        self.pool = self.urls - responsedURLs
                        change = False
```

This can work for us for now, but we need a more proper method to do this. A method sensitive to scrapper's pitfalls and crashes that can push again a task that is prone to not be completed by the assigned slave process of a scrapper. We could try not to push the same task to a scrapper twice, of course this would need to involve the scrapper to.

**Describe the solution you'd like**
I like a probabilistic method:

Let:
- `s` be the probability of a scrapper's slave process does not complete its task, 
- `p` the number of times that the dispacher push a single task, 
- `n` the number of scrappers that can pull the task,
- `P` the probability of that at least one task is completed.

We can set `P(s, p, n) = 1 - s^(min(p, n))`

Assuming that `s` is very low, we can find a proper value of `p` for that the expected value of `P` is acceptable given that `n` will not be too large.

Thus we can push a task `p` times from time to time as long as it has not been succefully completed and sended by a scrapper. 

If all the non completed task are pushed their `p` times, we can think on another way to complete this tasks.

The scrapper will know if a task is already being executed by one of his slaves in order to notify the dispacher to push again the task since he is already working on it.

**Describe alternatives you've considered**
Feel free to comment and propose a different solution, or improve the previous.

**Comment by e1Ru1o** [comment]
New solution:

The dispatcher can maintain the status of his `url` list, which could be.
```
0            =>  not pushed
1            => pushed
addr       => processed in addr
```
All task with status `0` will be pushed and changed to status `1`.

Then when a worker pulls a task, he will notify the client that requested it.

Then when a worker pulls a task, he will notify the client that requested it. That action change the related url status to addr, the address of the worker.

After that the client will be in charge of checking the work periodically. If the order is not being processed, he will change the status of the `url` to `0`  in order to push it again.

**Comment by AntiD2ta** [comment]
Issue reopened for upgrading and refactoring purposes
